# Generated by Django 4.1.2 on 2022-11-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='totalPrice',
            field=models.CharField(default='Total Price', max_length=50),
        ),
    ]
