# Generated by Django 4.1.3 on 2022-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='termName',
            field=models.CharField(default='blank', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unique_reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
