# Generated by Django 4.1.2 on 2022-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='students',
            field=models.CharField(default='', max_length=150, verbose_name='Register a student for these lessons.'),
        ),
    ]
