# Generated by Django 3.2.5 on 2022-11-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_num',
            new_name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='reference_num',
        ),
    ]
