# Generated by Django 4.1.2 on 2022-12-06 10:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
                ('child_name', models.CharField(default='', max_length=50, verbose_name="Student's name")),
                ('child_age', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)], verbose_name="Student's age")),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='child_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_students',
        ),
    ]
