# Generated by Django 4.1.2 on 2022-12-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='unique_reference_number',
            field=models.CharField(max_length=100),
        ),
    ]
