# Generated by Django 3.2.5 on 2022-12-07 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termName', models.CharField(default='blank', max_length=50)),
                ('startDate', models.DateField(default=datetime.date.today, unique=True)),
                ('endDate', models.DateField(default=datetime.date.today, unique=True)),
            ],
        ),
    ]
