# Generated by Django 4.1.3 on 2022-12-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_invoice_unique_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultChildRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.CharField(max_length=50)),
                ('adult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.adult')),
            ],
        ),
    ]
