# Generated by Django 4.1.2 on 2022-12-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_invoice_unique_reference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='number_of_lessons',
        ),
    ]
