# Generated by Django 4.1.2 on 2022-12-06 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_child_remove_user_child_age_remove_user_child_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
