# Generated by Django 3.2.5 on 2022-11-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20221127_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.CharField(default='68', max_length=6),
            preserve_default=False,
        ),
    ]
