# Generated by Django 3.2.5 on 2022-11-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_schoolbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
