# Generated by Django 4.1.2 on 2022-11-24 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_date', models.DateTimeField(default=datetime.date.today)),
                ('availability_time', models.TimeField(default='08:00')),
                ('number_of_lessons', models.CharField(max_length=3)),
                ('interval_between_lessons', models.CharField(max_length=3)),
                ('duration_of_lessons', models.CharField(choices=[('0', '30'), ('1', '60'), ('2', '90'), ('3', '120')], max_length=1)),
                ('instrument', models.CharField(blank=True, choices=[('0', 'violin'), ('1', 'double bass'), ('2', 'cello')], max_length=1)),
                ('teacher', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
