# Generated by Django 4.1.2 on 2022-12-02 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='endDate',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='startDate',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
