# Generated by Django 4.1.2 on 2022-12-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_invoice_unique_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currently_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval_between_lessons',
            field=models.CharField(choices=[('1', 1), ('2', 2)], max_length=2),
        ),
    ]
