# Generated by Django 4.1.3 on 2022-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_adultchildrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Adult Status'),
        ),
    ]
