# Generated by Django 4.1.2 on 2022-12-03 10:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_term_enddate_alter_term_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='availability_date',
            field=models.DateField(default=datetime.date(2022, 12, 3)),
        ),
        migrations.AlterField(
            model_name='request',
            name='interval_between_lessons',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_lessons',
            field=models.IntegerField(max_length=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
