# Generated by Django 4.1.2 on 2022-11-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20221123_2032'),
        ('lessons', '0003_request'),
    ]

    operations = [
    ]
