# Generated by Django 4.1.2 on 2022-12-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_request_number_of_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='interval_between_lessons',
            field=models.CharField(choices=[('1', 1), ('2', 2)], max_length=2),
        ),
    ]
