# Generated by Django 4.1.2 on 2022-12-05 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_request_interval_between_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='endDate',
            field=models.DateField(default=datetime.date(2022, 10, 23), unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='startDate',
            field=models.DateField(default=datetime.date(2022, 9, 1), unique=True),
        ),
    ]
