# Generated by Django 4.1.2 on 2022-11-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_merge_0003_auto_20221123_2032_0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration_of_lessons',
            field=models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90'), ('120', '120')], max_length=4),
        ),
        migrations.AlterField(
            model_name='request',
            name='instrument',
            field=models.CharField(blank=True, choices=[('violin', 'violin'), ('double bass', 'double bass'), ('cello', 'cello')], max_length=180),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
