# Generated by Django 4.1.1 on 2022-11-25 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_user_dateofbirth'),
        ('lessons', '0004_merge_0003_auto_20221123_2032_0003_request'),
    ]

    operations = [
    ]
