# Generated by Django 4.1.3 on 2022-12-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_adultchildrelationship_adult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'verbose_name': 'Adult'},
        ),
    ]
