# Generated by Django 4.1.1 on 2022-11-25 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_merge_20221125_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration_of_lessons',
            field=models.CharField(choices=[('30', '30'), ('60', '60'), ('90', '90'), ('120', '120')], max_length=4),
        ),
        migrations.AlterField(
            model_name='request',
            name='instrument',
            field=models.CharField(blank=True, choices=[('violin', 'violin'), ('double bass', 'double bass'), ('cello', 'cello')], max_length=180),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(verbose_name='Admin Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(verbose_name='Director Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid email')], verbose_name='email'),
        ),
    ]
