# Generated by Django 4.1.1 on 2022-12-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_user_is_adult'),
        ('lessons', '0005_alter_term_enddate_alter_term_startdate'),
    ]

    operations = [
    ]
