# Generated by Django 4.1.2 on 2022-11-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_request_duration_of_lessons_and_more'),
        ('lessons', '0006_alter_request_duration_of_lessons_and_more'),
    ]

    operations = [
    ]
