# Generated by Django 4.1.2 on 2022-12-06 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_merge_20221206_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adult',
            options={'verbose_name': 'Adult'},
        ),
        migrations.AlterField(
            model_name='term',
            name='endDate',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='startDate',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
