# Generated by Django 4.1.1 on 2022-12-06 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_invoice_unique_reference_number_and_more'),
        ('lessons', '0006_merge_20221206_1325'),
    ]

    operations = [
    ]
