# Generated by Django 4.1.2 on 2022-11-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_merge_20221128_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='duration_of_lessons',
            field=models.CharField(choices=[('30', '30'), ('45', '45'), ('60', '60')], max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateOfBirth',
            field=models.DateField(blank=True, max_length=8, null=True, verbose_name='Date of Birth'),
        ),
    ]
